name: Build and Deploy Docs to Netlify

on:
  push:
    paths:
      - "src/**/*.md"
jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: yarn install
      - run: yarn build-docs
      - uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_DOCS_SITE_ID }}
        with:
          args: deploy --dir=docs
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_DOCS_SITE_ID"]'
