name: Build and Deploy Storybook to Netlify

on:
  push:
    paths:
      - "src/stories/**/*.stories.js"
jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: yarn install
      - run: yarn build-storybook
      - uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_STORYBOOK_SITE_ID }}
        with:
          args: deploy --dir=storybook-static
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_STORYBOOK_SITE_ID"]'
